language: node_js
node_js:
  - '10'
  - '8'
before_install:
  - npm install -g npm@6
install: npm install
before_script:
  - npm run lint
after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
